config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :voters
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root "voters#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :voters
end

app/models/voter.rb
class Voter < ApplicationRecord
  belongs_to :user, optional: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  def home
  end
  
end

app/controllers/voters_controller.rb
class VotersController < ApplicationController
  before_action :set_voter, only: [:show, :edit, :update, :destroy]

  # GET /voters
  # GET /voters.json
  def index
    @voters = Voter.all
  end

  # GET /voters/1
  # GET /voters/1.json
  def show
  end

  # GET /voters/new
  def new
    @voter = Voter.new
  end

  # GET /voters/1/edit
  def edit
  end

  # POST /voters
  # POST /voters.json
  def create
    @voter = Voter.new(voter_params)

    respond_to do |format|
      if @voter.save
        format.html { redirect_to @voter, notice: 'Voter was successfully created.' }
        format.json { render :show, status: :created, location: @voter }
      else
        format.html { render :new }
        format.json { render json: @voter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /voters/1
  # PATCH/PUT /voters/1.json
  def update
    respond_to do |format|
      if @voter.update(voter_params)
        format.html { redirect_to @voter, notice: 'Voter was successfully updated.' }
        format.json { render :show, status: :ok, location: @voter }
      else
        format.html { render :edit }
        format.json { render json: @voter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /voters/1
  # DELETE /voters/1.json
  def destroy
    @voter.destroy
    respond_to do |format|
      format.html { redirect_to voters_url, notice: 'Voter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_voter
      @voter = Voter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def voter_params
      params.require(:voter).permit(:first_name, :last_name, :phone_number, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/voters_helper.rb
module VotersHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "CALLER", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!--<li class="active"><a href="#">About Us<span class="sr-only">(current)</span></a></li>-->
        <!--<li><a href="#">Contact</a></li>-->
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">About Us<span class="sr-only"></span></a></li>
        <li><a href="#">Contact</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
          <ul class="dropdown-menu">
          <% if current_user %>
          <li><%= link_to "New User", new_user_registration_path %></li>
            <li><%= link_to 'New Voter', new_voter_path %></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Sign Out</a></li>
          <% else %>
            <li><%= link_to 'Sign In User', new_user_session_path %></li>
            <li><%= link_to "Sign In Voter", new_user_registration_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Register", new_user_registration_path %></li>
          <% end %>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Caller</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <div class="col-md-10 col-md-offset-1">
          <%= render 'layouts/navbar' %>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/home.html.erb
<h1>This is the Home Page</h1>

app/views/voters/_form.html.erb
<%= form_for(voter) do |f| %>
  <% if voter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(voter.errors.count, "error") %> prohibited this voter from being saved:</h2>

      <ul>
      <% voter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <% unless Rails.env.test? %>
    <div class="field">
      <%= f.hidden_field :user_id %>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/voters/edit.html.erb
<h1>Editing Voter</h1>

<%= render 'form', voter: @voter %>

<%= link_to 'Show', @voter %> |
<%= link_to 'Back', voters_path %>

app/views/voters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Voters</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Phone number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @voters.each do |voter| %>
      <tr>
        <td><%= voter.first_name %></td>
        <td><%= voter.last_name %></td>
        <td><%= voter.phone_number %></td>
        <td><%= link_to 'Show', voter %></td>
        <td><%= link_to 'Edit', edit_voter_path(voter) %></td>
        <td><%= link_to 'Destroy', voter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user %>
<%= link_to 'New Voter', new_voter_path %> |
<%= link_to "New User", new_user_registration_path %>
<% end %>

app/views/voters/new.html.erb
<h1>New Voter</h1>

<%= render 'form', voter: @voter %>

<%= link_to 'Back', voters_path %>

app/views/voters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @voter.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @voter.last_name %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @voter.phone_number %>
</p>

<%= link_to 'Edit', edit_voter_path(@voter) %> |
<%= link_to 'Back', voters_path %>